### ISSUE TITLE
How to get the description file of entities

### ISSUE THREAD

**Issue by AndDoIt** [zjunlp/KNN-KG#6]
Could you please tell me how to obtain the description file of entities? It seems that the download FB15k-237 zip file does not have this description file.

**Comment by CheaSim** [comment]
We obtain the description files from the KG-BERT repo https://github.com/yao8839836/kg-bert, and you can get the file in our `dataset/FB15k-237` folder as `entity2text.txt`.

**Comment by AndDoIt** [comment]
Got it. Thx!
