### ISSUE TITLE
第三阶段如何跑通

### ISSUE THREAD

**Issue by wangyiyibo** [zjunlp/KNN-KG#7]
你好，我在复现您KNN代码中遇到一些问题，麻烦您看一下可以吗。就是第三阶段跑的是training里面version几 ，我这里有好几个version 而且每个version下还有多个文件

**Comment by CheaSim** [comment]
你好，第三阶段可以运行脚本中的`inference.sh`，利用`get_knowledge_store.sh`得到的faiss.dump文件来进行推理。

**Comment by wangyiyibo** [comment]
好的，谢谢您的回答，我还有一个疑问，checkpoint_path="the model stored in training"这个保存的模型是哪个



| |
王一博
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月31日 14:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zjunlp/KNN-KG] 第三阶段如何跑通 (Issue #7) |

你好，第三阶段可以运行脚本中的inference.sh，利用get_knowledge_store.sh得到的faiss.dump文件来进行推理。

**Comment by CheaSim** [comment]
我们模型命名以结果命名，一般在完成代码后，会print一个`best_model checkpoint path`这个路径，可以参考这个路径中的模型来给后续任务使用。

checkpoint_path="the model stored in training" 这句话是在哪里，模型保存都是使用同一套代码，除了knowledge store是硬编码存储在`dataset`每个数据集文件夹下的。

**Comment by wangyiyibo** [comment]
嗯嗯，好，感谢感谢



| |
王一博
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月31日 22:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zjunlp/KNN-KG] 第三阶段如何跑通 (Issue #7) |

我们模型命名以结果命名，一般在完成代码后，会print一个best_model checkpoint path这个路径，可以参考这个路径中的模型来给后续任务使用。

checkpoint_path="the model stored in training" 这句话是在哪里，模型保存都是使用同一套代码，除了knowledge store是硬编码存储在dataset每个数据集文件夹下的。
