### ISSUE TITLE
一个关于features的问题

### ISSUE THREAD

**Issue by quanhangbo** [zjunlp/KNN-KG#8]
您好，最近在阅读您的论文，运行代码时发现在进行Entity Embedding Initialization时，Epoch 0 进行到50%的时候，出现KeyError: 'label'，查看了代码后发现是data_module.py的DataCollatorForSeq2Seq类的__init__方法中features处理问题，当lables不存在的时候会产生错误，我尝试了多种方法，依然无法运行，想询问您如何去解决这个问题

**Comment by CheaSim** [comment]
请问您使用的是哪一个脚本，可能会因为数据集的选择产生问题。
